# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from acme_grpc_detector.detector.v1 import detector_pb2 as detector_dot_v1_dot_detector__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in detector/v1/detector_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DetectorServiceStub:
    """Detector service definition for gRPC sidecar plugins.
    Third-party detectors implement this service (DESIGN.md Section 7.3.1).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Initialize = channel.unary_unary(
                '/z_llm_safety_gateway.detector.v1.DetectorService/Initialize',
                request_serializer=detector_dot_v1_dot_detector__pb2.InitializeRequest.SerializeToString,
                response_deserializer=detector_dot_v1_dot_detector__pb2.InitializeResponse.FromString,
                _registered_method=True)
        self.Detect = channel.unary_unary(
                '/z_llm_safety_gateway.detector.v1.DetectorService/Detect',
                request_serializer=detector_dot_v1_dot_detector__pb2.DetectRequest.SerializeToString,
                response_deserializer=detector_dot_v1_dot_detector__pb2.DetectResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/z_llm_safety_gateway.detector.v1.DetectorService/HealthCheck',
                request_serializer=detector_dot_v1_dot_detector__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=detector_dot_v1_dot_detector__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/z_llm_safety_gateway.detector.v1.DetectorService/Shutdown',
                request_serializer=detector_dot_v1_dot_detector__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=detector_dot_v1_dot_detector__pb2.ShutdownResponse.FromString,
                _registered_method=True)


class DetectorServiceServicer:
    """Detector service definition for gRPC sidecar plugins.
    Third-party detectors implement this service (DESIGN.md Section 7.3.1).
    """

    def Initialize(self, request, context):
        """Initialize the detector with configuration.
        Called once at gateway startup.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Detect(self, request, context):
        """Execute detection on content.
        Called for each request that reaches this detector.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check. Called periodically by the gateway.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Graceful shutdown. Called when the gateway is shutting down.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DetectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Initialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialize,
                    request_deserializer=detector_dot_v1_dot_detector__pb2.InitializeRequest.FromString,
                    response_serializer=detector_dot_v1_dot_detector__pb2.InitializeResponse.SerializeToString,
            ),
            'Detect': grpc.unary_unary_rpc_method_handler(
                    servicer.Detect,
                    request_deserializer=detector_dot_v1_dot_detector__pb2.DetectRequest.FromString,
                    response_serializer=detector_dot_v1_dot_detector__pb2.DetectResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=detector_dot_v1_dot_detector__pb2.HealthCheckRequest.FromString,
                    response_serializer=detector_dot_v1_dot_detector__pb2.HealthCheckResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=detector_dot_v1_dot_detector__pb2.ShutdownRequest.FromString,
                    response_serializer=detector_dot_v1_dot_detector__pb2.ShutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'z_llm_safety_gateway.detector.v1.DetectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('z_llm_safety_gateway.detector.v1.DetectorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DetectorService:
    """Detector service definition for gRPC sidecar plugins.
    Third-party detectors implement this service (DESIGN.md Section 7.3.1).
    """

    @staticmethod
    def Initialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/z_llm_safety_gateway.detector.v1.DetectorService/Initialize',
            detector_dot_v1_dot_detector__pb2.InitializeRequest.SerializeToString,
            detector_dot_v1_dot_detector__pb2.InitializeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Detect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/z_llm_safety_gateway.detector.v1.DetectorService/Detect',
            detector_dot_v1_dot_detector__pb2.DetectRequest.SerializeToString,
            detector_dot_v1_dot_detector__pb2.DetectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/z_llm_safety_gateway.detector.v1.DetectorService/HealthCheck',
            detector_dot_v1_dot_detector__pb2.HealthCheckRequest.SerializeToString,
            detector_dot_v1_dot_detector__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/z_llm_safety_gateway.detector.v1.DetectorService/Shutdown',
            detector_dot_v1_dot_detector__pb2.ShutdownRequest.SerializeToString,
            detector_dot_v1_dot_detector__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
