"""stdd ci — Generate CI/CD config files and run deterministic failure checks."""
import argparse
import sys
import re
import json
import os
from pathlib import Path
from datetime import datetime


# Registry of check functions: each returns (status, message)
# status: "PASS" | "FAIL" | "WARN" | "SKIP"
CHECKS = []


def _register_check(fn):
    CHECKS.append(fn)
    return fn



GITHUB_WORKFLOW_TEMPLATE = """\
# STDD Quality Gate — Auto-generated by `stdd ci init`
# Version: {version}
# Generated: {date}

name: STDD Quality Gate

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]

jobs:
  stdd-quality:
    runs-on: ubuntu-latest
    # For Windows projects, change to: runs-on: windows-latest
    # and add 'shell: bash' to each step's run block
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '{python_version}'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov ruff

      - name: STDD Validate
        run: python bin/stdd validate

      - name: Run Tests with Coverage
        run: {test_command}

      - name: STDD Diff Check
        run: python bin/stdd diff

      - name: Lint Check
        run: {lint_command}

      - name: Type Check
        run: {typecheck_command}

      - name: STDD Failure Check
        run: python bin/stdd ci check-failures
"""

PRECOMMIT_TEMPLATE = """\
# STDD Pre-commit Hook — Auto-generated by `stdd ci init`
# Version: {version}
# Generated: {date}

repos:
  - repo: local
    hooks:
      - id: stdd-validate
        name: STDD Validate
        entry: python bin/stdd validate
        language: system
        pass_filenames: false
        stages: [commit]

      - id: stdd-lint
        name: STDD Lint
        entry: {lint_command}
        language: system
        pass_filenames: false
        types: [python]
        stages: [commit]
"""

PR_COMMENT_TEMPLATE = """\
## STDD Quality Gate Results

| Check | Status | Details |
|-------|--------|---------|
| Validate | {{ validate }} | Structure & spec format check |
| Tests | {{ tests }} | {{ test_summary }} |
| Coverage | {{ coverage }}% | Target: {{ coverage_target }}% |
| Diff | {{ diff }} | Spec ↔ Test ↔ Code traceability |
| Lint | {{ lint }} | Code style check |
| Failure Check | {{ failures }} | 11 failure modes (deterministic subset) |

{{ failure_details }}

---
📋 [Full Test Report]({{ test_report_url }}) · 📝 [Design Adjustments]({{ adjustments_url }})
"""


def _read_quality_config(project_root: Path) -> dict:
    """Read quality.yaml config."""
    from ..utils import read_config
    return read_config(project_root)


def _generate_workflow(project_root: Path, config: dict, dry_run: bool = False) -> str:
    ci_cfg = config.get("ci", {}).get("github_actions", {})
    python_version = ci_cfg.get("python_version", config.get("project", {}).get("python_version", "3.11"))
    test_cmd = ci_cfg.get("test_command", "pytest tests/ --cov=app --cov-report=xml --cov-report=term")
    lint_cmd = ci_cfg.get("lint_command", "ruff check app/ tests/")
    typecheck_cmd = ci_cfg.get("typecheck_command", "mypy app/")

    content = GITHUB_WORKFLOW_TEMPLATE.format(
        version="2.4",
        date=datetime.now().strftime("%Y-%m-%d"),
        python_version=python_version,
        test_command=test_cmd,
        lint_command=lint_cmd,
        typecheck_command=typecheck_cmd,
    )

    workflow_dir = project_root / ".github" / "workflows"
    workflow_path = workflow_dir / "stdd-quality.yml"

    if dry_run:
        print(f"\n  [DRY-RUN] 将创建: {workflow_path}")
        print("  ──────────────────────────────────────")
        print(content)
        return content

    workflow_dir.mkdir(parents=True, exist_ok=True)
    workflow_path.write_text(content, encoding="utf-8")
    print(f" 已创建: {workflow_path}")
    return content


def _generate_precommit(project_root: Path, config: dict, dry_run: bool = False) -> str:
    lint_cmd = config.get("quality", {}).get("lint", "ruff check app/ tests/")

    content = PRECOMMIT_TEMPLATE.format(
        version="2.4",
        date=datetime.now().strftime("%Y-%m-%d"),
        lint_command=lint_cmd,
    )

    precommit_path = project_root / ".pre-commit-config.yaml"

    if dry_run:
        print(f"\n  [DRY-RUN] 将创建: {precommit_path}")
        print("  ──────────────────────────────────────")
        print(content)
        return content

    if precommit_path.exists():
        existing = precommit_path.read_text(encoding="utf-8")
        if "STDD" in existing:
            print("  检测到已有 STDD pre-commit hook，跳过生成（避免覆盖现有配置）。")
            print("  如需重新生成，请先手动删除 .pre-commit-config.yaml 中的 STDD 段。")
            return content

        print("  检测到已有 .pre-commit-config.yaml，追加 STDD hook 段...")
        with open(precommit_path, "a", encoding="utf-8") as f:
            f.write("\n" + content)
        print(f" 已追加到: {precommit_path}")
        return content

    precommit_path.write_text(content, encoding="utf-8")
    print(f" 已创建: {precommit_path}")
    return content


def _generate_pr_template(project_root: Path, config: dict, dry_run: bool = False) -> str:
    github_dir = project_root / ".github"
    pr_path = github_dir / "stdd-pr-comment.md"

    if dry_run:
        print(f"\n  [DRY-RUN] 将创建: {pr_path}")
        print("  ──────────────────────────────────────")
        print(PR_COMMENT_TEMPLATE)
        return PR_COMMENT_TEMPLATE

    github_dir.mkdir(parents=True, exist_ok=True)
    pr_path.write_text(PR_COMMENT_TEMPLATE, encoding="utf-8")
    print(f" 已创建: {pr_path}")
    return PR_COMMENT_TEMPLATE


def _cmd_generate(args: argparse.Namespace, project_root: Path, config: dict) -> None:
    target = args.target
    dry_run = getattr(args, "dry_run", False)

    if target == "workflow":
        _generate_workflow(project_root, config, dry_run)
    elif target == "pre-commit":
        _generate_precommit(project_root, config, dry_run)
    elif target == "pr-template":
        _generate_pr_template(project_root, config, dry_run)
    else:
        print(f" 未知目标: {target}. 可用: workflow, pre-commit, pr-template")


def _cmd_init(args: argparse.Namespace, project_root: Path, config: dict) -> None:
    dry_run = getattr(args, "dry_run", False)
    print()
    if dry_run:
        print(" [DRY-RUN 模式] 预览将要创建的文件:\n")

    _generate_workflow(project_root, config, dry_run)
    _generate_precommit(project_root, config, dry_run)
    _generate_pr_template(project_root, config, dry_run)

    if dry_run:
        print("\n [DRY-RUN] 以上为预览，未实际创建任何文件。")
        print(" 去掉 --dry-run 以实际生成。")
    else:
        print()
        print(" STDD CI/CD 配置生成完成！")
        print(" 下一步：")
        print("   git add .github/ .pre-commit-config.yaml")
        print("   git commit -m 'chore: add STDD quality gate CI'")


def _cmd_check_failures(args: argparse.Namespace, project_root: Path) -> None:
    from ..finder import find_change_dir

    change_dir = find_change_dir(getattr(args, "name", None), project_root)
    if change_dir is None:
        print(f" 找不到 change: {getattr(args, 'name', None) or '(无)'}")
        sys.exit(1)

    results = []
    for check_fn in CHECKS:
        status, message = check_fn(change_dir, project_root)
        results.append((status, message))

    passed = [m for s, m in results if s == "PASS"]
    warnings = [m for s, m in results if s == "WARN"]
    skipped = [m for s, m in results if s == "SKIP"]
    errors = [m for s, m in results if s == "FAIL"]

    print()
    print("  STDD 失败模式检查结果 (CLI 确定性子集)")
    print(f"  {'─' * 50}")
    print(f"  ✅ 通过: {len(passed)}")
    print(f"  ⚠ 警告: {len(warnings)}")
    print(f"  ⏭ 跳过: {len(skipped)}")
    print(f"  ❌ 错误: {len(errors)}")

    if passed:
        print("\n  通过项:")
        for p in passed:
            print(f"    ✓ {p}")
    if warnings:
        print("\n  警告项:")
        for w in warnings:
            print(f"    ⚠ {w}")
    if skipped:
        print("\n  跳过项:")
        for s in skipped:
            print(f"    → {s}")
    if errors:
        print("\n  错误项:")
        for e in errors:
            print(f"    ✗ {e}")

    total = len(results)
    automated = len([s for s, _, in results if s != "SKIP"])
    print(f"\n  ──────────────────────────────────────")
    print(f"  自动化检查覆盖: {automated}/{total} 项")
    print(f"  完整 11 类检查（含语义分析）请使用 /stdd-verify")
    print()

    if errors:
        sys.exit(1)


# ── Registered check functions ────────────────────────────

@_register_check
def check_files_exist(change_dir: Path, _project_root: Path) -> tuple[str, str]:
    """(a) Check required files exist."""
    missing = []
    for f in ["proposal.md", "design.md", "test-plan.md", ".stdd.yaml"]:
        if not (change_dir / f).exists():
            missing.append(f)
    if missing:
        return ("FAIL", f"(a) 缺失文件: {', '.join(missing)}")
    specs_dir = change_dir / "specs"
    if specs_dir.exists() and any(specs_dir.rglob("*.md")):
        return ("PASS", "(a) 所有必需文件存在 + Spec 文件存在")
    return ("WARN", "(a) 必需文件存在，但 specs 目录为空")


@_register_check
def check_tcid_unique(change_dir: Path, _project_root: Path) -> tuple[str, str]:
    """(d) Check TC-ID uniqueness in test-plan.md."""
    test_plan = change_dir / "test-plan.md"
    if not test_plan.exists():
        return ("SKIP", "(d) test-plan.md 不存在，跳过 TC-ID 检查")
    content = test_plan.read_text(encoding="utf-8")
    tc_ids = re.findall(r"(TC-[A-Z]+-\d{3})", content)
    if not tc_ids:
        return ("WARN", "(d) 未找到 TC-ID")
    unique = set(tc_ids)
    duplicates = [tc for tc in unique if tc_ids.count(tc) > 1]
    if duplicates:
        return ("FAIL", f"(d) 重复 TC-ID: {duplicates}")
    return ("PASS", f"(d) TC-ID 唯一 ({len(unique)} 个)")


@_register_check
def check_shall_keyword(change_dir: Path, _project_root: Path) -> tuple[str, str]:
    """(f) Check THEN statements contain SHALL keyword."""
    specs_dir = change_dir / "specs"
    if not specs_dir.exists():
        return ("SKIP", "(f) specs 目录不存在，跳过 SHALL 检查")
    spec_files = list(specs_dir.rglob("*.md"))
    if not spec_files:
        return ("SKIP", "(f) 无 spec 文件")
    issues = []
    for sf in spec_files:
        content = sf.read_text(encoding="utf-8")
        then_lines = re.findall(r"\*\*THEN\*\*\s*(.+?)(?:\n|$)", content)
        no_shall = [t for t in then_lines if "SHALL" not in t]
        if no_shall:
            issues.append(f"{sf.name}: {len(no_shall)} 处缺少 SHALL")
    if issues:
        return ("WARN", f"(f) SHALL 缺失: {', '.join(issues)}")
    return ("PASS", "(f) 所有 THEN 含 SHALL")


@_register_check
def check_and_count(change_dir: Path, _project_root: Path) -> tuple[str, str]:
    """(g) Check AND count per scenario."""
    specs_dir = change_dir / "specs"
    if not specs_dir.exists():
        return ("SKIP", "(g) specs 目录不存在")
    spec_files = list(specs_dir.rglob("*.md"))
    if not spec_files:
        return ("SKIP", "(g) 无 spec 文件")
    issues = []
    for sf in spec_files:
        content = sf.read_text(encoding="utf-8")
        and_count = len(re.findall(r"\*\*AND\*\*", content))
        if and_count > 5:
            issues.append(f"{sf.name}: AND 数量 {and_count}")
    if issues:
        return ("WARN", f"(g) AND 超限: {', '.join(issues)}")
    return ("PASS", "(g) AND 数量正常")


@_register_check
def check_scope_creep(change_dir: Path, _project_root: Path) -> tuple[str, str]:
    """(b) Check files changed match declared capabilities in proposal."""
    proposal_path = change_dir / "proposal.md"
    if not proposal_path.exists():
        return ("SKIP", "(b) proposal.md 不存在")

    content = proposal_path.read_text(encoding="utf-8")
    caps = re.findall(r"-\s*(?:STDD-MARKER:\s*)?capability:\s*(\S+)", content)
    if not caps:
        return ("SKIP", "(b) proposal 未声明 capability 列表")

    # Get changed files via git diff --stat
    import subprocess
    try:
        result = subprocess.run(
            ["git", "diff", "--stat", "HEAD~1"],
            capture_output=True, text=True, timeout=10,
            cwd=str(change_dir.parent.parent)
        )
        changed_files = result.stdout.strip()
    except Exception:
        return ("SKIP", "(b) 无法运行 git diff，跳过范围检查")

    if not changed_files:
        return ("PASS", "(b) 无文件变更")

    # Simple heuristic: check if changed files are in expected directories
    changed_paths = re.findall(r"^\s*([^\s|]+)", changed_files, re.MULTILINE)
    out_of_scope = []
    for fp in changed_paths:
        fp = fp.strip()
        # A file is in-scope if it's under one of the capability spec dirs
        # or in common dirs like .stdd/, tests/, etc.
        common_dirs = {".stdd/", "tests/", "docs/", ".github/"}
        is_common = any(fp.startswith(d) for d in common_dirs)
        is_cap = any(f"specs/{c}/" in fp or f"commands/{c}" in fp for c in caps)
        if not is_common and not is_cap:
            out_of_scope.append(fp)

    if out_of_scope:
        return ("WARN", f"(b) 范围蔓延: {len(out_of_scope)} 个文件可能超出声明范围 ({', '.join(out_of_scope[:3])}...)")
    return ("PASS", f"(b) 文件变更在声明范围内 ({len(caps)} capabilities)")


@_register_check
def check_coverage_vacuum(change_dir: Path, project_root: Path) -> tuple[str, str]:
    """(j) Check test coverage against threshold."""
    cov_path = project_root / "coverage.json"
    if not cov_path.exists():
        return ("SKIP", "(j) 无 coverage.json，跳过覆盖检查")

    try:
        cov_data = json.loads(cov_path.read_text(encoding="utf-8"))
        pct = cov_data.get("summary", {}).get("percent_covered", cov_data.get("totals", {}).get("percent_covered"))
        if pct is None:
            return ("SKIP", "(j) coverage.json 无 percent_covered 字段")
    except Exception:
        return ("SKIP", "(j) coverage.json 解析失败")

    # Read threshold from quality.yaml
    from ..utils import read_config
    config = read_config(project_root)
    threshold = config.get("quality", {}).get("coverage_threshold", 80)

    if pct >= threshold:
        return ("PASS", f"(j) 覆盖率 {pct:.1f}% >= {threshold}%")
    return ("FAIL", f"(j) 覆盖率不足: {pct:.1f}% < {threshold}%")


@_register_check
def check_contract_gap(change_dir: Path, project_root: Path) -> tuple[str, str]:
    """(k) Check contract consistency across capabilities."""
    specs_dir = change_dir / "specs"
    if not specs_dir.exists() or len(list(specs_dir.iterdir())) < 2:
        return ("SKIP", "(k) 少于 2 个 capability，跳过契约检查")

    # Build a map: capability_name -> set of defined fields/entities
    cap_fields = {}
    for cap_dir in specs_dir.iterdir():
        if not cap_dir.is_dir():
            continue
        spec_file = cap_dir / "spec.md"
        if not spec_file.exists():
            continue
        content = spec_file.read_text(encoding="utf-8")
        cap_name = cap_dir.name
        # Extract field definitions: words after "SHALL" patterns, Requirement names
        fields = set(re.findall(r"SHALL\s+(\w+)", content))
        # Also capture Requirement names
        reqs = set(re.findall(r"## Requirement:\s*(.+)", content))
        cap_fields[cap_name] = fields | reqs

    if len(cap_fields) < 2:
        return ("SKIP", "(k) 有效的 capability spec 不足，跳过契约检查")

    # Check cross-references: "GIVEN.*from <capability>" pattern
    gaps = []
    for cap_name, defined_fields in cap_fields.items():
        spec_file = specs_dir / cap_name / "spec.md"
        content = spec_file.read_text(encoding="utf-8")
        refs = re.findall(r"GIVEN.*from\s+(\S+)", content)
        for ref_cap in refs:
            ref_cap_clean = ref_cap.rstrip(".")
            if ref_cap_clean in cap_fields:
                # Check if referenced fields exist in the target capability
                ref_content = (specs_dir / ref_cap_clean / "spec.md").read_text(encoding="utf-8")
                # Extract field names referenced from target
                ref_fields = set(re.findall(r"GIVEN.*from\s+" + re.escape(ref_cap_clean) + r".*?(\w+)", content))
                target_fields = cap_fields[ref_cap_clean]
                missing = ref_fields - target_fields
                if missing and ref_fields:
                    gaps.append(f"{cap_name} -> {ref_cap_clean}: 引用未定义字段")

    if gaps:
        return ("FAIL", f"(k) 契约断层: {'; '.join(gaps[:3])}")
    return ("PASS", f"(k) 契约一致 ({len(cap_fields)} capabilities)")


def cmd_ci(args: argparse.Namespace) -> None:
    from ..utils import get_logger
    get_logger()

    project_root = Path.cwd()

    subcommand = args.subcommand if getattr(args, "subcommand", None) else "init"

    if subcommand == "init":
        config = _read_quality_config(project_root)
        _cmd_init(args, project_root, config)
    elif subcommand in ("generate", "gen"):
        config = _read_quality_config(project_root)
        _cmd_generate(args, project_root, config)
    elif subcommand == "check-failures":
        _cmd_check_failures(args, project_root)
    elif subcommand in ("check-scope", "check-coverage", "check-contracts"):
        _run_single_check(args, project_root, subcommand)
    else:
        print(f" 未知子命令: {subcommand}")
        print(" 可用: init, generate, check-failures, check-scope, check-coverage, check-contracts")
        sys.exit(1)


def _run_single_check(args: argparse.Namespace, project_root: Path, subcommand: str) -> None:
    """Run a single named check and report result."""
    from ..finder import find_change_dir

    change_dir = find_change_dir(getattr(args, "name", None), project_root)
    if change_dir is None:
        print(f" 找不到 change: {getattr(args, 'name', None) or '(无)'}")
        sys.exit(1)

    check_map = {
        "check-scope": check_scope_creep,
        "check-coverage": check_coverage_vacuum,
        "check-contracts": check_contract_gap,
    }
    fn = check_map[subcommand]
    status, message = fn(change_dir, project_root)
    symbol = {"PASS": "✓", "FAIL": "✗", "WARN": "⚠", "SKIP": "→"}
    print(f"  {symbol.get(status, '?')} [{status}] {message}")
    if status == "FAIL":
        sys.exit(1)


# ── V2.7 复盘新增: TC 计划 vs 实际测试对账 ─────────────────

@_register_check
def check_tc_implementation_coverage(change_dir: Path, project_root: Path) -> tuple[str, str]:
    """Check that test-plan TC-IDs have corresponding test implementations.

    This is the critical check that would have caught the V2.7 development failure:
    30 planned TCs had zero corresponding test functions.
    """
    test_plan = change_dir / "test-plan.md"
    if not test_plan.exists():
        return ("SKIP", "test-plan.md 不存在，跳过 TC 实现覆盖检查")

    # Extract TC-IDs from test plan
    content = test_plan.read_text(encoding="utf-8")
    planned_tcs = set(re.findall(r"(TC-[A-Z]+-\d{3})", content))
    if not planned_tcs:
        return ("SKIP", "test-plan.md 中未找到 TC-ID")

    # Search for TC-IDs in test files
    tests_dir = project_root / "tests"
    if not tests_dir.exists():
        return ("SKIP", "tests/ 目录不存在，跳过 TC 实现覆盖检查")

    implemented_tcs = set()
    for test_file in tests_dir.rglob("test_*.py"):
        file_content = test_file.read_text(encoding="utf-8")
        for tc_id in planned_tcs:
            if tc_id in file_content:
                implemented_tcs.add(tc_id)

    missing = planned_tcs - implemented_tcs
    coverage_pct = len(implemented_tcs) / len(planned_tcs) * 100 if planned_tcs else 100

    if not missing:
        return ("PASS", f"TC 实现覆盖: {len(implemented_tcs)}/{len(planned_tcs)} (100%)")

    if coverage_pct < 50:
        return ("FAIL", f"TC 实现覆盖严重不足: {len(implemented_tcs)}/{len(planned_tcs)} ({coverage_pct:.0f}%)。缺失: {', '.join(sorted(missing)[:5])}{'...' if len(missing) > 5 else ''}")

    return ("WARN", f"TC 实现覆盖: {len(implemented_tcs)}/{len(planned_tcs)} ({coverage_pct:.0f}%)。缺失: {', '.join(sorted(missing)[:5])}{'...' if len(missing) > 5 else ''}")


@_register_check
def check_anchoring_missing(change_dir: Path, project_root: Path) -> tuple[str, str]:
    """(l) Check critical Change has sufficient anchoring level (V2.7)."""
    import yaml as _yaml
    # Check for canonical proposal
    canon_file = project_root / "canonical" / "proposals" / f"{change_dir.name}.yaml"
    if not canon_file.exists():
        return ("SKIP", "(l) canonical proposal not found — cannot check anchoring")

    try:
        data = _yaml.safe_load(canon_file.read_text(encoding="utf-8"))
    except Exception:
        return ("SKIP", "(l) canonical proposal parse failed")

    critical = data.get("critical", {})
    if not critical.get("is_critical", False):
        return ("PASS", "(l) Non-critical change — anchoring not required")

    risk = critical.get("risk_assessment", {})
    required = "L1"
    if risk.get("financial"):
        required = "L4"
    elif risk.get("safety_critical"):
        required = "L3"
    elif risk.get("cross_system"):
        required = "L2"

    current = data.get("anchoring", {}).get("level", "L1")
    level_num = {"L1": 1, "L2": 2, "L3": 3, "L4": 4}

    if level_num.get(current, 1) < level_num.get(required, 1):
        return ("FAIL", f"(l) 锚定等级不足：当前 {current}，最低要求 {required}")
    return ("PASS", f"(l) Anchoring: {current} >= {required}")


@_register_check
def check_slice_completion(change_dir: Path, project_root: Path) -> tuple[str, str]:
    """Check that all slices marked 'done' have evidence (V2.7 post-mortem P4-3)."""
    stdd_yaml = change_dir / ".stdd.yaml"
    if not stdd_yaml.exists():
        return ("SKIP", ".stdd.yaml 不存在")

    import yaml as _yaml
    state = _yaml.safe_load(stdd_yaml.read_text(encoding="utf-8")) or {}
    slices = state.get("phase4", {}).get("slices_completed", {})
    if not slices:
        return ("SKIP", "无切片完成记录")

    unverified = []
    for slice_id, info in slices.items():
        if info.get("status") == "done":
            tc_cov = info.get("tc_coverage", "N/A")
            new_tests = info.get("new_tests", 0)
            verified_at = info.get("verified_at", "")
            if not verified_at or new_tests == 0:
                unverified.append(f"Slice {slice_id} (new_tests={new_tests}, verified_at={'set' if verified_at else 'missing'})")

    if unverified:
        return ("WARN", f"以下切片标记为 done 但缺少验证证据: {'; '.join(unverified)}")

    return ("PASS", f"{len(slices)} 个切片均有验证证据")


# ── V2.8: pass@k verification ──────────────────────────────

def run_pass_k(test_command: str, k: int = 3) -> dict:
    """Run tests k times and compute pass@k metrics.

    Returns dict with: pass_count, total, pass_at_1, pass_at_k, details
    """
    import subprocess
    results = []
    for i in range(k):
        result = subprocess.run(test_command, shell=True, capture_output=True, text=True)
        results.append(result.returncode == 0)

    return {
        "pass_count": sum(results),
        "total": k,
        "pass_at_1": 1.0 if results[0] else 0.0,
        "pass_at_k": sum(results) / k if k > 0 else 0.0,
        "details": results,
    }


def check_passk_ambiguity(pass_at_1: float, pass_at_k: float, k: int) -> str | None:
    """Detect spec ambiguity: pass@1 low but pass@k high.

    Returns warning message if ambiguity detected, None otherwise.
    """
    if k < 3:
        return None
    if pass_at_1 < 0.5 and pass_at_k > 0.8:
        return (f"⚠️  Spec 可能存在歧义 — pass@1={pass_at_1:.0%} 但 pass@{k}={pass_at_k:.0%}。"
                f"建议在 Phase 2 中提升锚定等级。")
    return None
